<?php
/**
 * @file
 * govi_mecanismos_contacto.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function govi_mecanismos_contacto_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-menu-mecanismos-de-contacto_correo-electrnico-para-notifcaciones-judiciales:transparencia/mecanismos-contacto/notificaciones-judiciales.
  $menu_links['menu-menu-mecanismos-de-contacto_correo-electrnico-para-notifcaciones-judiciales:transparencia/mecanismos-contacto/notificaciones-judiciales'] = array(
    'menu_name' => 'menu-menu-mecanismos-de-contacto',
    'link_path' => 'transparencia/mecanismos-contacto/notificaciones-judiciales',
    'router_path' => 'transparencia/mecanismos-contacto/notificaciones-judiciales',
    'link_title' => 'Correo electrónico para notifcaciones judiciales',
    'options' => array(
      'cami' => array(
        'pages' => '',
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'data-inner-width' => '',
        'data-inner-height' => '',
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-mecanismos-de-contacto_correo-electrnico-para-notifcaciones-judiciales:transparencia/mecanismos-contacto/notificaciones-judiciales',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-menu-mecanismos-de-contacto_localizacin-fsica-sucursales-o-regionales-horarios-y-das-de-atencin-al-pblico:transparencia/mecanismos-contacto/localizacion-fisica-horarios-atencion.
  $menu_links['menu-menu-mecanismos-de-contacto_localizacin-fsica-sucursales-o-regionales-horarios-y-das-de-atencin-al-pblico:transparencia/mecanismos-contacto/localizacion-fisica-horarios-atencion'] = array(
    'menu_name' => 'menu-menu-mecanismos-de-contacto',
    'link_path' => 'transparencia/mecanismos-contacto/localizacion-fisica-horarios-atencion',
    'router_path' => 'transparencia/mecanismos-contacto/localizacion-fisica-horarios-atencion',
    'link_title' => 'Localización física, sucursales o regionales, horarios y días de atención al público',
    'options' => array(
      'cami' => array(
        'pages' => '',
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'data-inner-width' => '',
        'data-inner-height' => '',
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-mecanismos-de-contacto_localizacin-fsica-sucursales-o-regionales-horarios-y-das-de-atencin-al-pblico:transparencia/mecanismos-contacto/localizacion-fisica-horarios-atencion',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-menu-mecanismos-de-contacto_mecanismos-de-atencin-a-la-ciudadana:transparencia/mecanismos-contacto/mecanismos-atencion-ciudadania.
  $menu_links['menu-menu-mecanismos-de-contacto_mecanismos-de-atencin-a-la-ciudadana:transparencia/mecanismos-contacto/mecanismos-atencion-ciudadania'] = array(
    'menu_name' => 'menu-menu-mecanismos-de-contacto',
    'link_path' => 'transparencia/mecanismos-contacto/mecanismos-atencion-ciudadania',
    'router_path' => 'transparencia/mecanismos-contacto/mecanismos-atencion-ciudadania',
    'link_title' => 'Mecanismos de atención a la ciudadanía',
    'options' => array(
      'cami' => array(
        'pages' => '',
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'data-inner-width' => '',
        'data-inner-height' => '',
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-mecanismos-de-contacto_mecanismos-de-atencin-a-la-ciudadana:transparencia/mecanismos-contacto/mecanismos-atencion-ciudadania',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-menu-mecanismos-de-contacto_polticas-de-seguridad-de-la-informacin-y-proteccin-de-datos-personales:transparencia/mecanismos-contacto/PSI-proteccion-datos-personales.
  $menu_links['menu-menu-mecanismos-de-contacto_polticas-de-seguridad-de-la-informacin-y-proteccin-de-datos-personales:transparencia/mecanismos-contacto/PSI-proteccion-datos-personales'] = array(
    'menu_name' => 'menu-menu-mecanismos-de-contacto',
    'link_path' => 'transparencia/mecanismos-contacto/PSI-proteccion-datos-personales',
    'router_path' => 'transparencia/mecanismos-contacto/PSI-proteccion-datos-personales',
    'link_title' => 'Políticas de seguridad de la información y protección de datos personales',
    'options' => array(
      'cami' => array(
        'pages' => '',
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'data-inner-width' => '',
        'data-inner-height' => '',
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-mecanismos-de-contacto_polticas-de-seguridad-de-la-informacin-y-proteccin-de-datos-personales:transparencia/mecanismos-contacto/PSI-proteccion-datos-personales',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Correo electrónico para notifcaciones judiciales');
  t('Localización física, sucursales o regionales, horarios y días de atención al público');
  t('Mecanismos de atención a la ciudadanía');
  t('Políticas de seguridad de la información y protección de datos personales');

  return $menu_links;
}
